# Generated by Django 5.0.3 on 2024-03-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.product'),
        ),
    ]
