# Generated by Django 5.0 on 2023-12-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
