# Generated by Django 5.0 on 2023-12-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricehistory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=20)),
                ("description", models.CharField(default=None, max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="productdetail",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.productdetail",
            ),
            preserve_default=False,
        ),
    ]
