# Generated by Django 5.0.3 on 2024-03-26 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_date_pricehistory_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.product'),
        ),
    ]
