# Generated by Django 5.0 on 2023-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_productdetail_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="description",
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
