# Generated by Django 5.0 on 2023-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
