# Generated by Django 5.0 on 2023-12-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_product_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricehistory",
            name="productdetail",
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.product",
            ),
            preserve_default=False,
        ),
    ]
